### ISSUE TITLE
[Request] Make timeintervals configurable per target

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.snmp#105]
**Describe the solution you'd like**
The poll intervall should be adjustable per target. Some devices must be polled frequently (i.e. network equipment) while others do not update data frequently and hence only need a much lower poll frequency (i.e. a printer)

**Describe alternatives you've considered**
One could use multiple instances of sbnmp Adapter. But this would use more resources.

**Additional context**
see https://forum.iobroker.net/post/770938  (@baenker)

**Comment by Baenker** [comment]
Die Beschreibung trifft es ganz gut.

**Comment by mcm1957** [comment]
fixed at release 2.0.0
