### ISSUE TITLE
Adapter does not update values after error

### ISSUE THREAD

**Issue by ivosch68** [iobroker-community-adapters/ioBroker.snmp#116]
**Precondition**
I have maintained two OIDs in the configuration settings of the snmp adapter:

1. 1.3.6.1.2.1.43.10.2.1.4.1.1 (pages total)
2. 1.3.6.1.2.1.43.18.1.1.7.1.1 (alert code)

The second OID is only available, as long as an error is present. Otherwise it is null.

**Observed Behavior**
In case of an error on my printer, the snmp adapter works like expected and return values for both OIDs, but as soon as no error is present, and hence the second OID is not available, the message 

> session.get: RequestFailedError: NoSuchName: 1.3.6.1.2.1.43.18.1.1.7.1.1

shows up in the log (which is expected). 
_At the same moment the other value will not be updated and the instance remains in a yellow (not connected) state._

**Expected Behavior**
If an OIDis not available or if the value of an OID is undefined/null, catch and log the error, but continue with the processing of the remaining OIDs.

**Remark**
I did a test with a second instance of the adapter only having the first OID maintained. This value is updated correctly,

Please come back to me in case of questions. I will be happy to support.

And ... A big thank you for the creation and maintanance of this adapter!

**Comment by mcm1957** [comment]
fixed with release 2.1.0
