### ISSUE TITLE
Netzwerkgeräte die nicht 24/7 laufen Fehler im Log

### ISSUE THREAD

**Issue by Baenker** [iobroker-community-adapters/ioBroker.snmp#12]
ich habe einen Drucker eingebunden. Alles funktioniert wie es soll nur wenn der Drucker ausgestellt ist, wird das Log mit Warnings geflutet weil das Gerät nicht erreichbar ist.

Keine Ahnung ob das nur bei mir so ist oder überall. Ein richtiger Fehler ist es ja nicht, weil das Gerät ja wirklich nicht erreichbar ist. Trotzdem ist es in dem Fall für mich unnötig

Am Sinnvollsten wäre vor Abfrage der Datenpunkte abzufragen ob Gerät erreichbar ist (per Ping oder Ping-Adapter bzw Datenpunkt vom Ping-Adapter) und wenn Gerät nicht erreichbar dann einfach beim nächstenmal wieder probieren. Einen Fehler im Log ist zur Fehleranalyse ist zwar sinnvoll aber in dem Fall ist es ja kein Fehler, da Gerät bewusst ausgeschaltet ist. Evtl Zusatzoption in Einstellungen um bei Inbetriebnahme erstmal alles zu loggen. So kann man die Option hinterher wieder deaktivieren.

Derzeit ist der Adapter für mich nur mit Geräten nutzbar die 24/7 laufen. Dort arbeitet der Adapter richtig gut und ich bin sehr begeistert von diesen Adapter.

**Comment by CTJaeger** [comment]
Hallo. Ich baue diese Funktion in den nächsten Tagen ein. Vielen Dank für das Feedback.

**Comment by Meinsda** [comment]
Hallo

Hab auch das gleiche Problem! Wäre toll wenn man das log pro Eintrag aktivieren kann und auf eine ip adresse auch ein flag kontraktierbar hätte.

**Comment by mcm1957** [comment]
Das Verhalten für Geräte die nicht 24h online sind wurde verbessert.
Siehe PR für 0.6.2.
Bis dieser PR gemerged wird kannst du ggF und auf eigenes Risiko meine Version direkt von Github installieren: 
https://github.com/mcm1957/ioBroker.snmp/tree/V0.6.2

Diskussion siehe
https://forum.iobroker.net/topic/52735/anf%C3%A4nger-snmp-adapter-fragen-ver%C3%B6ffentlichung-v-updates/31

**Comment by Apollon77** [comment]
Please retry upcoming 0.6.3

**Comment by mcm1957** [comment]
fixed in release v1.0.0
