### ISSUE TITLE
Namen mit 2 Leerstellen werden nicht ausgelesen

### ISSUE THREAD

**Issue by RK62** [iobroker-community-adapters/ioBroker.snmp#14]
Wenn ein Name mit mehr als einer Leerstelle verwendet wird, funktioniert das Auslesen des SNMP Wertes nicht.

Beispiel:
**eins zwei** wird zu  **snmp.0.10_0_0_204.eins_zwei** mit einem Wert
**eins zwei drei** wird zu **snmp.0.10_0_0_204.eins_zwei drei** ohne dass ein Wert eingetragen wird
**eins_zwei_drei** wird zu **snmp.0.10_0_0_204.eins_zwei_drei** und funktioniert

Wahrscheinlich muss der der entsprechende replace alle Leerzeichen ersetzen und nicht nur das erste.

Gruß, Ralf

**Comment by Apollon77** [comment]
Please retry upcoming 0.6.3

**Comment by mcm1957** [comment]
fixed in release v1.0.0
