### ISSUE TITLE
Sortieren der Einträge führt zum Datenverlust alle Punkte

### ISSUE THREAD

**Issue by RK62** [iobroker-community-adapters/ioBroker.snmp#15]
Wenn man die Einträge mit den Pfeilen verschieben möchte, ist die ganze Liste leer. Entweder verlässt man die Konfiguration mit **Abbrechen** oder man verliert durch das Speichern alle Datenpunkte.
Nur der Pfeil beim ersten Eintrag funktioniert wie gewünscht.

Gruß, Ralf

**Comment by mcm1957** [comment]
fixed with release 2.0.0
Admin rewritten to use jsonConfig / Admin 5.x.x Interface
