### ISSUE TITLE
Dezimalwerte können scheinbar nicht ausgelesen werden

### ISSUE THREAD

**Issue by RK62** [iobroker-community-adapters/ioBroker.snmp#16]
Bei Strings und ganzzahligen Einträgen funktioniert das Auslesen der SNMP-Werte einwandfrei.
Bei Werten mit Nachkommastellen (mit Dezimalpunkt) scheint es noch ein Problem zu geben:

Werte aus dem MIB-Browser:
![2018-05-21 16_47_54-ireasoning mib browser-esk01](https://user-images.githubusercontent.com/39200469/40314884-25c336e8-5d1a-11e8-8fc5-9355f7ee828a.png)

Zuordnung im Admin:
![2018-05-21 17_14_14-iobroker admin-esk01](https://user-images.githubusercontent.com/39200469/40315021-85f91d52-5d1a-11e8-9e73-8b2ccb445b4e.png)

Darstellung im ioBroker:
![2018-05-21 17_15_46-microsoft edge-esk01](https://user-images.githubusercontent.com/39200469/40315123-cdf5ccfe-5d1a-11e8-823b-89af7a38d4c5.png)

Gruß, Ralf

**Comment by RK62** [comment]
Mittlerweile habe ich herausgefunden, dass die Hex-Werte im _Opaque-Format_ abgelegte Zahlen sind. Habe auch eine Umrechnung gefunden, die jedoch nur manchmal funktioniert. Ich nehme an, dass der Wert durch die Ablage im String verfälscht wird. 

Könnte also den Code liefern wenn das jemand hier in GitHub anpasst. Da fehlen mir leider noch die Kenntnisse.

Gruß, Ralf

**Comment by integer63** [comment]
Gib es hierzu schon eine Lösung? Ich habe das selbe Problem:
![snmp-glyphen](https://user-images.githubusercontent.com/35612711/73052804-4c9b3000-3e86-11ea-9072-afe90d1d4e9c.png)

**Comment by Apollon77** [comment]
Please retry upcoming 0.6.3

**Comment by RK62** [comment]
The problem also exists under the new version of iobroker-community-adapters/ioBroker.snmp V1.0.0

**Comment by mcm1957** [comment]
fixed with v2.1.2

Due to veri limited sources retourning floating point values, any test and feedback is very welcome.
Tested with Synology DSM V6

**Comment by mcm1957** [comment]
> Gib es hierzu schon eine Lösung? Ich habe das selbe Problem: ![snmp-glyphen](https://user-images.githubusercontent.com/35612711/73052804-4c9b3000-3e86-11ea-9072-afe90d1d4e9c.png) Nur, dass es sich hier um Integer Zahlen (64 bit) handelt.

See https://github.com/iobroker-community-adapters/ioBroker.snmp/issues/57 - fixed with v2.1.0

**Comment by mcm1957** [comment]
fixed with v2.1.2

**Comment by RK62** [comment]
Works realy fine, Thanks!

**Comment by mcm1957** [comment]
Thanks for the fedback.
