### ISSUE TITLE
Improvement: Datapoints handling

### ISSUE THREAD

**Issue by Scrounger** [iobroker-community-adapters/ioBroker.snmp#19]
@CTJaeger 
Can you please implement a better datapoint handling to support sub folders.
For example if add in setup a datapoint "Farbe.Schwarz", the object will has the name "Farbe_Schwarz".

So if the adapter could handle dots and create sub datapoints, it will be easier to support multiple devices.

**Comment by mcm1957** [comment]
fixed in release v1.0.0
