### ISSUE TITLE
[Request] Add option to not create `-type` states

### ISSUE THREAD

**Issue by EvilEls** [iobroker-community-adapters/ioBroker.snmp#218]
The adapter creates unnecessary `-type` data points for every OID.
Could you please introduce an option to make the adapter NOT create the `-type` data points?

![grafik](https://user-images.githubusercontent.com/29343914/211843962-f9a62f97-2a0f-443b-afa8-5c4886ee744f.png)

**Comment by mcm1957** [comment]
Thanks for the feedback.

I added those states for two reasons:
a) An easy way to inform th user about the kind of native data reported by the device. This could be useful for writeable oids.
b) As a first step on the way to support writeable oids. Writing to an oid need knowledge about the format of the oid data to send. But meantime I store this kind of information internal so the adapter does not need those states any more.

I will consider removing or making optional those states with the next release.

**Comment by mcm1957** [comment]
implemented at v2.4.0

You can now control creation of -type states at panle "options"

**Comment by EvilEls** [comment]
Thank you! 👍😀

**Comment by mcm1957** [comment]
Your welcome.
Please let me know whether everything works fine if you are willing (and have time / resources) to test the lates/bety 2.4.0

**Comment by EvilEls** [comment]
2.4.0 is working flawlessly! 
Thank you very much! 🙏

```
snmp.0 | 2023-02-22 11:12:37.137 | info | adapter initializing, chunk size set to 20
snmp.0 | 2023-02-22 11:12:36.168 | info | removing states *-type...
snmp.0 | 2023-02-22 11:12:36.036 | info | starting. Version 2.4.0 in /opt/iobroker/node_modules/iobroker.snmp, node: v16.19.0, js-controller: 4.0.24
snmp.0 | 2023-02-22 11:12:31.889 | info | Terminated (NO_ERROR): exit after migration of config
snmp.0 | 2023-02-22 11:12:31.888 | info | installation completed
snmp.0 | 2023-02-22 11:12:31.887 | info | instance system.adapter.snmp.0 already up to date
snmp.0 | 2023-02-22 11:12:31.852 | info | performing installation
snmp.0 | 2023-02-22 11:12:31.849 | info | starting. Version 2.4.0 in /opt/iobroker/node_modules/iobroker.snmp, node: v16.19.0, js-controller: 4.0.24
```

![image](https://user-images.githubusercontent.com/29343914/220591503-4ee3d3d6-f2de-418b-9a1d-0da1dac21c34.png)


![image](https://user-images.githubusercontent.com/29343914/220591452-542af145-7604-4841-90f6-00115d26dec2.png)
