### ISSUE TITLE
Please add export/import of  configuration

### ISSUE THREAD

**Issue by Homoran** [iobroker-community-adapters/ioBroker.snmp#29]
An adapter with so many manual settings should have the possibility to export and reimport the settings.

for instance if  you setup the adapter for a synology SMART it woul be fine to configure one disk than export the config and edit the json by copy and replace for the other 7 Disks

Or if you'll move from the testing system to the productive systems

**Comment by mcm1957** [comment]
Import  / Export should be available per default with admin 5.
Functionality has still to be tested

**Comment by mcm1957** [comment]
Export / Import of config data is now a standrad feature of admin adapter. So no change in snmp is required.

Please note that import is working starting with admin v6.2.22
See https://github.com/ioBroker/ioBroker.admin/issues/1686
