### ISSUE TITLE
Änderung kann nicht gespeichert werden

### ISSUE THREAD

**Issue by chris47803** [iobroker-community-adapters/ioBroker.snmp#332]
Hallo.

Ich kann Änderungen in diesem Adapter nicht mehr speichern.
Die Buttons sind da und lassen sich anklicken, aber nichts passiert.

Weder im Firefox, Edge noch Chrome.

LG
Chris

**Comment by chris47803** [comment]
Thank you

**Comment by mcm1957** [comment]
The relactes (real) cause of the problem is tracked here:
https://github.com/ioBroker/ioBroker.admin/issues/2124
