### ISSUE TITLE
Speichern der Konfiguration nicht möglich, Buttons rot umrandet

### ISSUE THREAD

**Issue by Shadrasi1** [iobroker-community-adapters/ioBroker.snmp#388]
Ich habe heute den snmp-Adapter installiert, um mein Synology-NAS zu überwachen. Allerdings kann ich keine Konfiguration abspeichern, da die drei Buttons "Speichern", "Speichern und Schließen" und "Schließen" rot umrandet sind. Nirgendwo anders in den Adapter-Einstellungen steht ein Fehlertext.
Neuinstallation schon getestet
Mein Vorgehen:
-Adapter installiert und Adaptereinstellungen geöffnet
-OID-Gruppe in erstem Tab erstellt und korrekt eingetragen
-OID-Gerät konfiguriert mit korrekter Version, OID-Gruppe und Community
-Leere Autorisierungstabelle erstellt wie im ioBroker-Forum gefunden

![grafik](https://github.com/iobroker-community-adapters/ioBroker.snmp/assets/155895776/4c39374e-b88d-4b9e-9788-3cbe0154ebbe)
Admin-Version 6.12

![grafik](https://github.com/iobroker-community-adapters/ioBroker.snmp/assets/155895776/6b507fcc-8d9c-4e00-a096-d5331aa3fe0a)

![grafik](https://github.com/iobroker-community-adapters/ioBroker.snmp/assets/155895776/39cabecb-c33a-4cb2-b05b-a7284eb8f408)

**Comment by Shadrasi1** [comment]
Nach mind. 15 Minuten warten - Tab im Hintergrund - gingen die roten Umrandungen weg und ich konnte es abspeichern. Wenn ich jetzt noch Änderungen durchführe, kann ich es ebenfalls sofort speichern.

**Comment by mcm1957** [comment]
Bitte Versionen angeben:

adapter 
admin (6.12 gibts nicht, da fehlen Ziffern)
js-controller
node

Bitte auch checken ob der Workaround lt. gepinntem Issue https://github.com/iobroker-community-adapters/ioBroker.snmp/issues/332 hilft. Es muss hier ein Dummy Eintrag erfolgen.

Weiters bitte checken ob in der Browserconsole ein fehler gelogged wird.

**Comment by mcm1957** [comment]
Könnte durch diesen Fhler in admin ausgelöst worden sein.
https://github.com/ioBroker/ioBroker.admin/issues/2340

**Comment by mcm1957** [comment]
Falls das Problem nochmals auftritt, bitte um Feedback / Reopen / neues Issue.
