### ISSUE TITLE
Please add support for objects of type Counter64

### ISSUE THREAD

**Issue by rekorboi** [iobroker-community-adapters/ioBroker.snmp#57]
OIDs of type Counter64 are commonly used for SNMP monitoring, see e.g. “Synology DiskStation MIB Guide” (https://global.download.synology.com/download/Document/Software/DeveloperGuide/Firmware/DSM/All/enu/Synology_DiskStation_MIB_Guide.pdf).

Requests for Counter64 OIDs with ioBroker.snmp v0.5.0 result in “NoSuchName” errors. Counter64 appears to have been introduced in SNMPv2.

See also https://forum.iobroker.net/topic/8155/adapter-snmp-drucker-synology-qnap-etc-auslesen/156.

**Comment by Apollon77** [comment]
Please retry upcoming 0.6.3

**Comment by mcm1957** [comment]
@rekorboi  Could you or someone else please list any Synology OID which should return counter64?
I've scanned my synology (DMS 6.x) with iReasoning MIB Browser (win 10) but it did not report any counter 64 oid !?

Mayby the MIB browser has a 64bit problem too - but it would be helpful to know a "working" counter64 oid

**Comment by mcm1957** [comment]
.1.3.6.1.4.1.6574.102.1.1.12.1 is an example for a counter64 value presented by Synology NAS DSM 6.x

**Comment by mcm1957** [comment]
counter64 type requires ssnmpv2 (or later). 

So this issue can be fixed with next release only.

**Comment by mcm1957** [comment]
fixed with release 2.1.0
