### ISSUE TITLE
[Feature] Add SNMPv3

### ISSUE THREAD

**Issue by SThomae** [iobroker-community-adapters/ioBroker.snmp#71]
Please add support for SNMPv3.

**Comment by Apollon77** [comment]
Please retry upcoming 0.6.3

**Comment by Apollon77** [comment]
.. but I fear it will not work out of the box and need more changes to config

**Comment by mcm1957** [comment]
Sorry 
I'm quite sure that 0.6.3 will NOT (yet) support 0.6.3.
McM

**Comment by mcm1957** [comment]
Implementation Note: 
Todo - check Authorization config to be compatible not only for SNMP V3 cleint but also for Server / Trap support to avoid later Config changes

**Comment by mcm1957** [comment]
Change released with release 2.2.1
