### ISSUE TITLE
Error session.get: RequestFailedError: TooBig

### ISSUE THREAD

**Issue by JBSullivan** [iobroker-community-adapters/ioBroker.snmp#72]
Auf bitte von Apollon77 lege ich hier mal ein issue zum dem SNMP  Adapter an
das Thema wird im Forum im Link unten behandelt. Adapter Version ist 0.5.0, der Rest vom System siehe Screenshot.

![image](https://user-images.githubusercontent.com/44617472/115896678-f7204b00-a45b-11eb-85d9-cc8bf8f24265.png)

![image](https://user-images.githubusercontent.com/44617472/115896368-a3156680-a45b-11eb-982e-1ac0e417084b.png)

Konkret geht es darum, das OID`s welche mit einem MIB Browser direkt aus der USV ausgelesen wurden, nur manchmal dargestellt werden.

Besonders Auffällig, ist hier der blau markierte Bereich im MIB Browser. Es handelt sich beides mal um ein Datum als Ergebniss.

Im SNMP sieht das dann so aus (Nr. 3 & Nr.20). Leider wird nicht mehr als DEBUG ausgegeben.

`
snmp.0 | 2021-04-23 17:51:49.742 | error | (7224) [10.122.60.87] Error session.get: RequestFailedError: TooBig
-- | -- | -- | --
snmp.0 | 2021-04-23 17:51:19.762 | error | (7224) [10.122.60.87] Error session.get: RequestFailedError: TooBig
snmp.0 | 2021-04-23 17:51:19.734 | debug | (7224) [10.122.60.87] OIDs: 1.3.6.1.4.1.318.1.1.1.1.1.1.0, 1.3.6.1.4.1.318.1.1.1.1.2.1.0, 1.3.6.1.4.1.318.1.1.1.1.2.2.0, 1.3.6.1.4.1.318.1.1.1.1.2.3.0, 1.3.6.1.4.1.318.1.1.1.2.2.2.0, 1.3.6.1.4.1.318.1
snmp.0 | 2021-04-23 17:51:19.351 | info | (7224) starting. Version 0.5.0 in C:/iobroker/GLT/node_modules/iobroker.snmp, node: v14.16.0, js-controller: 3.2.16
host.GLT(GLT) | 2021-04-23 17:51:17.948 | info | instance system.adapter.snmp.0 started with pid 7224

![image](https://user-images.githubusercontent.com/44617472/115897224-7c0b6480-a45c-11eb-829d-f5c3dc7ceb78.png)
 
https://forum.iobroker.net/topic/44381/usv-per-snmp-auslesen/13?_=1619189361118

**Comment by Apollon77** [comment]
Please retry upcoming 0.6.3

**Comment by JBSullivan** [comment]
Ich habe gerade mal aus dem GIT die 0.6.2 ausprobiert. Bitte in der 0.6.3 darauf achten, das der Unterstrich ( _ ) bei der Erzeugung der Datenpunkt Namen erhalten bleibt.

Die 0.6.2 legt alle DP Namen neu an, allerdings ohne den Unterstrich bei durch Leerzeichen getrennten DP Namen !!

![image](https://user-images.githubusercontent.com/44617472/159185386-7eafc9ad-371d-4415-bc69-96d089918ffc.png)

**Comment by Apollon77** [comment]
Der GitHub stand wird eine 1.0 und "breaked" potentiell die Objektstrukturc... Am Ende werden wohl alle leerzeichen zu "_" ... also kommt da noch ein Change (so als ankündigung) ... gern nchmal jetzt von Github, denke so wird es

**Comment by Apollon77** [comment]
PS: Alles andere war maximal inkonsistent ... 
Übrigens "." bleibt jetzt "nicht ersetzt" sodas  man eigene strukturen anlegen kann

**Comment by mcm1957** [comment]
Die Fehlermeldung kommt eindeutig direkt aus dem net-snmp Package. Das soll aber nicht heißen, dass nicht der Adapter was falsch macht und das Verhalten auslöst.

Wenn möglich, bitte das Verhalten mit der aktuellen v1.0.0 (latest Repo) verifizieren. 
**Achtung:** lastest Repo == use at own risk.

Weiters wäre ich sehr dankbar, wenn jemand weiß wie dieser Fehler reproduzierbra ist (oder sein könnte). Ich hab leider keine USV. Ich kann nur Lexmark Laserprinter, einige Synology NAS (DSM 6.x) und einen kleinen Netgear GS308T anbieten.

**Comment by mcm1957** [comment]
Cause of problem detected:
https://forum.iobroker.net/topic/44381/usv-per-snmp-auslesen/22

The number of OIDs read within one request is limited. According to topic in forum a numer of 20 oids is the limit.

Solution would be to split requests

**Comment by mcm1957** [comment]
fixed with release v2.1.3
