### ISSUE TITLE
Timeout Error seit Admin 5.0.11

### ISSUE THREAD

**Issue by JBSullivan** [iobroker-community-adapters/ioBroker.snmp#73]
Ich weiß nicht, ob es in direkten Zusammenhang steht, jedoch bekomme ich seit dem Update auf Admin 5.0.11 Timeout Error .

Weder am Gerät noch an den Adapter Einstellungen wurde etwas geändert. Der Adapter lief seit ca. 2 Wochen ohne Probleme bzgl. eines TimeOut Errors.

Das hier ist alles was man als DEBUG bekommt.

`

  |   |   |  
-- | -- | -- | --
snmp.0 | 2021-05-02 07:02:55.248 | error | (11732) [10.122.60.87] Error session.get: RequestTimedOutError: Request timed out
snmp.0 | 2021-05-02 07:02:45.230 | debug | (11732) [10.122.60.87] OIDs: 1.3.6.1.4.1.318.1.1.1.1.1.1.0, 1.3.6.1.4.1.318.1.1.1.1.2.1.0, 1.3.6.1.4.1.318.1.1.1.1.2.2.0, 1.3.6.1.4.1.318.1.1.1.1.2.3.0, 1.3.6.1.4.1.318.1.1.1.2.2.2.0, 1.3.6.1.4.1.318.
snmp.0 | 2021-05-02 07:02:45.080 | info | (11732) starting. Version 0.5.0 in C:/iobroker/GLT/node_modules/iobroker.snmp, node: v14.16.0, js-controller: 3.3.5
host.GLT(GLT) | 2021-05-02 07:02:43.601 | info | instance system.adapter.snmp.0 started with pid 11732

`

`

  |   |   |  
-- | -- | -- | --
snmp.0 | 2021-05-02 06:57:56.867 | error | (8316) [10.122.60.87] Error session.get: RequestTimedOutError: Request timed out
snmp.0 | 2021-05-02 06:57:26.866 | error | (8316) [10.122.60.87] Error session.get: RequestTimedOutError: Request timed out
snmp.0 | 2021-05-02 06:56:56.859 | error | (8316) [10.122.60.87] Error session.get: RequestTimedOutError: Request timed out
snmp.0 | 2021-05-02 06:56:26.857 | error | (8316) [10.122.60.87] Error session.get: RequestTimedOutError: Request timed out

`

**Comment by mcm1957** [comment]
Most likely this waning occures whenever ip 10.122.60.87 is nog reachable.

Theres a new PR for 0.6.1 which improves this behavior as unreachable destinations o longer raise an error at every poll intervall but only log one info for this event. 

Feel free to test this new version - downloadable form mcm1957/ioBroker.smnp.

**Comment by Apollon77** [comment]
Please retry upcoming 0.6.3

**Comment by mcm1957** [comment]
fixed in release v1.0.0
